#pragma once

/* Auto-generated by WinVersion - Nullriver Software - http://www.nullriver.com */

#define MAJOR 1
#define MINOR 0
#define RELEASE 1
#define BUILD 55
#define VERSION_STRING "1.0.1.55"
